// Exact port from saga_calc/assets/scripts/systems/systemsData.js

export interface SubsystemParams {
  [key: string]: number;
}

export interface SubsystemDef {
  min: number;
  max: number;
  params: SubsystemParams;
}

export interface SystemDef {
  name: string;
  minWidth: number;
  maxWidth: number;
  maxFullWidth?: number;
  extraField?: boolean;
  subsystems: Record<string, SubsystemDef>;
}

const angleParams: Record<string, SubsystemParams> = {
  "(1)+1C+1C+(1)": {
    doors: 4, rails: 2, side_rail_caps_45: 2,
    bottom_double_caps: 1, bottom_single_caps: 2,
    rail_to_rail_connectors: 2, rail_to_cap_connectors: 10,
    handles: 4, door_brush_joint: 4,
    cap_no_brush: 2, cap_with_brush: 4, corner_cap: 2,
    moving_mechanism_dovodchik: 1, moving_mechanism_belt_connector: 1,
    adapter_belt: 0, bottom_rollers: 1, corner_rubber_joint: 0,
    fixed_door_profile: 2, fixed_mechanism: 2, width_adjustment: 32,
  },
  "1+2C+2C+1": {
    doors: 6, rails: 3, side_rail_caps_45: 2,
    bottom_double_caps: 2, bottom_single_caps: 2,
    rail_to_rail_connectors: 4, rail_to_cap_connectors: 12,
    handles: 4, door_brush_joint: 8,
    cap_no_brush: 2, cap_with_brush: 8, corner_cap: 2,
    moving_mechanism_dovodchik: 1, moving_mechanism_belt_connector: 1,
    adapter_belt: 2, bottom_rollers: 2, corner_rubber_joint: 0,
    fixed_door_profile: 2, fixed_mechanism: 2, width_adjustment: 70,
  },
};

const cascadeParams: Record<string, SubsystemParams> = {
  "3+0": {
    num_doors:3, num_rails:3, num_side_caps:2,
    num_bottom_double_caps:2, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:4, num_rail_to_cap_connectors:10,
    num_handles:4, door_brush:4,
    profile_cap_no_brush:2, profile_cap_with_brush:4,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:1,
    belt_adapter:0, bottom_rollers:1, corner_rubber_joint:0,
  },
  "4+0": {
    num_doors:4, num_rails:4, num_side_caps:2,
    num_bottom_double_caps:3, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:6, num_rail_to_cap_connectors:12,
    num_handles:4, door_brush:6,
    profile_cap_no_brush:2, profile_cap_with_brush:6,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:2,
    belt_adapter:2, bottom_rollers:2, corner_rubber_joint:0,
  },
  "5+0": {
    num_doors:5, num_rails:5, num_side_caps:2,
    num_bottom_double_caps:4, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:8, num_rail_to_cap_connectors:14,
    num_handles:4, door_brush:8,
    profile_cap_no_brush:2, profile_cap_with_brush:8,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:3,
    belt_adapter:3, bottom_rollers:3, corner_rubber_joint:0,
  },
  "6+0": {
    num_doors:6, num_rails:6, num_side_caps:2,
    num_bottom_double_caps:5, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:10, num_rail_to_cap_connectors:16,
    num_handles:4, door_brush:10,
    profile_cap_no_brush:2, profile_cap_with_brush:10,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:4,
    belt_adapter:4, bottom_rollers:4, corner_rubber_joint:0,
  },
  "7+0": {
    num_doors:7, num_rails:7, num_side_caps:2,
    num_bottom_double_caps:6, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:12, num_rail_to_cap_connectors:18,
    num_handles:4, door_brush:12,
    profile_cap_no_brush:2, profile_cap_with_brush:12,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:5,
    belt_adapter:5, bottom_rollers:5, corner_rubber_joint:0,
  },
  "8+0": {
    num_doors:8, num_rails:8, num_side_caps:2,
    num_bottom_double_caps:7, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:14, num_rail_to_cap_connectors:20,
    num_handles:4, door_brush:14,
    profile_cap_no_brush:2, profile_cap_with_brush:14,
    profile_C_cap:0, profile_V_cap:0,
    moving_mechanism_ci:2, belt_connector_mechanism:6,
    belt_adapter:6, bottom_rollers:6, corner_rubber_joint:0,
  },
  "3+0|3+0": {
    num_doors:6, num_rails:3, num_side_caps:2,
    num_bottom_double_caps:2, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:4, num_rail_to_cap_connectors:10,
    num_handles:8, door_brush:8,
    profile_cap_no_brush:2, profile_cap_with_brush:8,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:2,
    belt_adapter:0, bottom_rollers:2, corner_rubber_joint:1,
  },
  "4+0|4+0": {
    num_doors:8, num_rails:4, num_side_caps:2,
    num_bottom_double_caps:3, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:6, num_rail_to_cap_connectors:12,
    num_handles:8, door_brush:12,
    profile_cap_no_brush:2, profile_cap_with_brush:12,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:4,
    belt_adapter:4, bottom_rollers:4, corner_rubber_joint:1,
  },
  "5+0|5+0": {
    num_doors:10, num_rails:5, num_side_caps:2,
    num_bottom_double_caps:4, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:8, num_rail_to_cap_connectors:14,
    num_handles:8, door_brush:16,
    profile_cap_no_brush:2, profile_cap_with_brush:16,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:6,
    belt_adapter:6, bottom_rollers:6, corner_rubber_joint:1,
  },
  "6+0|6+0": {
    num_doors:12, num_rails:6, num_side_caps:2,
    num_bottom_double_caps:5, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:10, num_rail_to_cap_connectors:16,
    num_handles:8, door_brush:20,
    profile_cap_no_brush:2, profile_cap_with_brush:20,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:8,
    belt_adapter:8, bottom_rollers:8, corner_rubber_joint:1,
  },
  "7+0|7+0": {
    num_doors:14, num_rails:7, num_side_caps:2,
    num_bottom_double_caps:6, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:12, num_rail_to_cap_connectors:18,
    num_handles:8, door_brush:24,
    profile_cap_no_brush:2, profile_cap_with_brush:24,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:10,
    belt_adapter:10, bottom_rollers:10, corner_rubber_joint:1,
  },
  "8+0|8+0": {
    num_doors:16, num_rails:8, num_side_caps:2,
    num_bottom_double_caps:7, num_bottom_single_caps:2,
    num_rail_to_rail_connectors:14, num_rail_to_cap_connectors:20,
    num_handles:8, door_brush:28,
    profile_cap_no_brush:2, profile_cap_with_brush:28,
    profile_C_cap:1, profile_V_cap:1,
    moving_mechanism_ci:4, belt_connector_mechanism:12,
    belt_adapter:12, bottom_rollers:12, corner_rubber_joint:1,
  },
};

export const systemsData: Record<string, SystemDef> = {
  angle: {
    name: 'Двери с угловым примыканием',
    minWidth: 1615,
    maxWidth: 6000,
    subsystems: {
      '(1)+1C+1C+(1)': { min: 1615, max: 4500, params: angleParams['(1)+1C+1C+(1)'] },
      '1+2C+2C+1': { min: 2145, max: 6000, params: angleParams['1+2C+2C+1'] },
    },
  },
  'embedded-wall': {
    name: 'Врезанные в стену двери',
    extraField: true,
    minWidth: 550,
    maxWidth: 6000,
    subsystems: {
      '2+0': { min:1068, max:3000, params:{
        num_doors:2, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:2, door_brush:2,
        profile_cap_no_brush:2, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism_ci:1, belt_connector_mechanism:1,
        belt_adapter:0, bottom_rollers:1,
        gap_rubber:0, capWithBrush:2, push_mechanism:0,
        gap_base_profile:0, gap_basic_cap_profile:0,
        gap_deco_cap_profile:0, inner_support_profile:0,
        corner_rubber_joint:0,
      }},
      '2+0|2+0': { min:2115, max:6000, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:2, door_brush:2,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism_ci:2, belt_connector_mechanism:2,
        belt_adapter:2, bottom_rollers:2,
        gap_rubber:1, capWithBrush:4, push_mechanism:0,
        gap_base_profile:0, gap_basic_cap_profile:0,
        gap_deco_cap_profile:0, inner_support_profile:0,
        corner_rubber_joint:1,
      }},
      '1WPUSH': { min:550, max:1500, params:{
        num_doors:1, num_rails:1, num_side_caps:2,
        num_bottom_double_caps:0, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:6,
        num_handles:2, door_brush:2,
        profile_cap_no_brush:3, profile_cap_with_brush:0,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism_ci:1, belt_connector_mechanism:0,
        belt_adapter:3, bottom_rollers:0,
        gap_rubber:0, capWithBrush:0, push_mechanism:1,
        gap_base_profile:2, gap_basic_cap_profile:2,
        gap_deco_cap_profile:2, inner_support_profile:1,
      }},
      '2WPUSH': { min:1084, max:3000, params:{
        num_doors:2, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:2, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism_ci:1, belt_connector_mechanism:1,
        belt_adapter:4, bottom_rollers:1,
        gap_rubber:0, capWithBrush:2, push_mechanism:1,
        gap_base_profile:2, gap_basic_cap_profile:2,
        gap_deco_cap_profile:2, inner_support_profile:1,
      }},
    },
  },
  sync: {
    name: 'Синхронные двери',
    minWidth: 2200,
    maxWidth: 9000,
    subsystems: {
      '(1)+1S+1S+(1)': { min:2200, max:6000, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:1, fixed_mechanism:2,
        fixed_door_profile:2, moving_mechanism_tros:1,
      }},
      '1+1S+1S+1': { min:2200, max:7500, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:3, fixed_mechanism:0,
        fixed_door_profile:0, moving_mechanism_tros:1,
      }},
      '(1)+(1)+1S+1S+(1)+(1)': { min:3350, max:9000, params:{
        num_doors:6, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:6, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:1, fixed_mechanism:4,
        fixed_door_profile:4, moving_mechanism_tros:1,
      }},
    },
  },
  cascade: {
    name: 'Каскадные двери',
    minWidth: 1615,
    maxWidth: 12000,
    subsystems: {
      '3+0': { min: 1615, max: 4500, params: cascadeParams['3+0'] },
      '4+0': { min: 2145, max: 6000, params: cascadeParams['4+0'] },
      '5+0': { min: 2680, max: 6000, params: cascadeParams['5+0'] },
      '6+0': { min: 3147, max: 6000, params: cascadeParams['6+0'] },
      '7+0': { min: 3745, max: 6000, params: cascadeParams['7+0'] },
      '8+0': { min: 4278, max: 6000, params: cascadeParams['8+0'] },
      '3+0|3+0': { min: 3230, max: 9000, params: cascadeParams['3+0|3+0'] },
      '4+0|4+0': { min: 4295, max: 12000, params: cascadeParams['4+0|4+0'] },
      '5+0|5+0': { min: 5360, max: 12000, params: cascadeParams['5+0|5+0'] },
      '6+0|6+0': { min: 6425, max: 12000, params: cascadeParams['6+0|6+0'] },
      '7+0|7+0': { min: 7490, max: 12000, params: cascadeParams['7+0|7+0'] },
      '8+0|8+0': { min: 8555, max: 12000, params: cascadeParams['8+0|8+0'] },
    },
  },
  unlinked: {
    name: 'Не связанные двери',
    minWidth: 500,
    maxWidth: 6000,
    subsystems: {
      '(1)': { min:500, max:2400, params:{
        num_doors:1, num_rails:1, num_side_caps:2,
        num_bottom_double_caps:0, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:0, num_rail_to_cap_connectors:6,
        num_moving_mechanisms:0, num_fixed_mechanisms:1,
        num_handles:0, door_brush:0,
        profile_cap_no_brush:2, profile_cap_with_brush:0,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:0, fixed_mechanism:1,
        fixed_door_profile:1, door_brush_joint:0,
      }},
      '1': { min:500, max:2400, params:{
        num_doors:1, num_rails:1, num_side_caps:2,
        num_bottom_double_caps:0, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:0, num_rail_to_cap_connectors:6,
        num_moving_mechanisms:1, num_fixed_mechanisms:0,
        num_handles:2, door_brush:0,
        profile_cap_no_brush:2, profile_cap_with_brush:0,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:1, fixed_mechanism:0,
        fixed_door_profile:0, door_brush_joint:0,
      }},
      '(1)+1': { min:1000, max:2400, params:{
        num_doors:2, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:1, num_fixed_mechanisms:1,
        num_handles:0, door_brush:2,
        profile_cap_no_brush:2, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:1, fixed_mechanism:1,
        fixed_door_profile:1, door_brush_joint:0,
      }},
      '1+1': { min:1000, max:2400, params:{
        num_doors:2, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:2, num_fixed_mechanisms:0,
        num_handles:4, door_brush:2,
        profile_cap_no_brush:2, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:2, fixed_mechanism:0,
        fixed_door_profile:0, door_brush_joint:0,
      }},
      '(1)+1+(1)': { min:1500, max:3600, params:{
        num_doors:3, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:1, num_fixed_mechanisms:2,
        num_handles:2, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:1, fixed_mechanism:2,
        fixed_door_profile:2, door_brush_joint:0,
      }},
      '1+1+1': { min:1500, max:3600, params:{
        num_doors:3, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:3, num_fixed_mechanisms:0,
        num_handles:6, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:3, fixed_mechanism:0,
        fixed_door_profile:0, door_brush_joint:0,
      }},
      '(1)+1+1+(1)': { min:2000, max:6000, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:2, num_fixed_mechanisms:2,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:2, fixed_mechanism:2,
        fixed_door_profile:2, door_brush_joint:1,
      }},
      '1+1+1+1': { min:2000, max:6000, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_moving_mechanisms:4, num_fixed_mechanisms:0,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:2, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:4, fixed_mechanism:0,
        fixed_door_profile:0, door_brush_joint:1,
      }},
    },
  },
  'wall-mounted': {
    name: 'Настенные двери',
    extraField: true,
    minWidth: 500,
    maxWidth: 3000,
    maxFullWidth: 6000,
    subsystems: {
      'Система 1W': { min:500, max:1500, params:{
        num_doors:1,
        num_rails_41:1, num_rails_47:0,
        num_side_caps_45:2, num_side_caps_51:0,
        num_bottom_single_caps:2, num_bottom_double_caps:0,
        num_rrconn:0, num_rcconn:6,
        num_handles:2,
        profile_cap_no_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        n_ci:1, n_ct:0,
        corner_rubber_joint:0,
        door_brush:0, fixed_door_profile:0,
        door_width_offset:16,
      }},
      'Система 1W+1W': { min:1000, max:3000, params:{
        num_doors:2,
        num_rails_41:1, num_rails_47:0,
        num_side_caps_45:2, num_side_caps_51:0,
        num_bottom_single_caps:2, num_bottom_double_caps:0,
        num_rrconn:0, num_rcconn:6,
        num_handles:4,
        profile_cap_no_brush:2,
        profile_C_cap:1, profile_V_cap:1,
        n_ci:2, n_ct:0,
        corner_rubber_joint:1,
        door_brush:0, fixed_door_profile:0,
        door_width_offset:32,
      }},
      'Система 1SW+1SW': { min:1000, max:3000, params:{
        num_doors:2,
        num_rails_41:0, num_rails_47:1,
        num_side_caps_45:0, num_side_caps_51:2,
        num_bottom_single_caps:2, num_bottom_double_caps:0,
        num_rrconn:0, num_rcconn:6,
        num_handles:4,
        profile_cap_no_brush:2,
        profile_C_cap:1, profile_V_cap:1,
        n_ci:1, n_ct:1,
        corner_rubber_joint:1,
        door_brush:0, fixed_door_profile:1,
        door_width_offset:17,
      }},
    },
  },
  partition: {
    name: 'Стена-перегородка',
    minWidth: 2400,
    maxWidth: 9000,
    subsystems: {
      '(1)+(1)+(1)+1': { min:2400, max:6000, params:{
        num_doors:4, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:2, door_brush:2,
        profile_cap_no_brush:6, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:1, fixed_mechanism:3,
        fixed_door_profile:3, door_width_offset:16,
      }},
      '(1)+(1)+(1)+(1)+1': { min:3000, max:7500, params:{
        num_doors:5, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:2, door_brush:2,
        profile_cap_no_brush:8, profile_cap_with_brush:2,
        profile_C_cap:0, profile_V_cap:0,
        moving_mechanism:1, fixed_mechanism:4,
        fixed_door_profile:4, door_width_offset:16,
      }},
      '(1)+(1)+1+1+(1)+(1)': { min:3600, max:9000, params:{
        num_doors:6, num_rails:2, num_side_caps:2,
        num_bottom_double_caps:1, num_bottom_single_caps:2,
        num_rail_to_rail_connectors:2, num_rail_to_cap_connectors:8,
        num_handles:4, door_brush:4,
        profile_cap_no_brush:6, profile_cap_with_brush:4,
        profile_C_cap:1, profile_V_cap:1,
        moving_mechanism:2, fixed_mechanism:4,
        fixed_door_profile:4, door_width_offset:17,
      }},
    },
  },
};

/** Get available subsystems for a given system and width */
export function getAvailableSubsystems(
  systemKey: string,
  width: number
): string[] {
  const system = systemsData[systemKey];
  if (!system) return [];
  const checkWidth = width;
  return Object.entries(system.subsystems)
    .filter(([, sub]) => checkWidth >= sub.min && checkWidth <= sub.max)
    .map(([key]) => key);
}
